### ISSUE TITLE
Get transaction id from paypal sdk 2.0.1.

### ISSUE THREAD

**Issue by Nik6015** [paypal/PayPal-iOS-SDK#125]
How to get Transaction id from paypal sdk 2.0.1, i searched a lot but i am stuck at getting transaction id from paypal sdk 2.0.1.

check response below;-
```js
{
client =
 {
    environment = sandbox;
    "paypal_sdk_version" = "2.0.1";
    platform = iOS;
    "product_name" = "PayPal iOS SDK";
 };
response =  
  {
    "create_time" = "2014-04-01T07:02:34Z";
    id = "PAY-3J588144TJ947892HKM5GJCQ";
    intent = sale;
    state = approved;
  };
"response_type" = payment;
 }
```
Above code i got pay id but not getting transaction id, how can i get transaction id.???

anybody please give me right suggestion.

**Comment by daxeshzwt** [comment]
How to get Transcation id in Android Paypal SDK :
I have just found below json response from paypal.
{
client =
{
environment = sandbox;
"paypal_sdk_version" = "2.0.1";
platform = android;
"product_name" = "PayPal android SDK";
};
response =

{
"create_time" = "2014-04-01T07:02:34Z";
id = "PAY-3J588144TJ947892HKM5GJCQ";
intent = sale;
state = approved;
};
"response_type" = payment;
}

i want to need transaction id  not pay id . so please help me how to get it using Android PayPal SDK.
i was enable to call rest API to get transaction id  because there have issues of secure establish
OR 

If you have another way to get it.

**Comment by bluk** [comment]
@daxeshzwt For future Android questions, you should use the [PayPal Android SDK Issues](https://github.com/paypal/PayPal-Android-SDK/issues).

Are you unable to call the REST API get the Transaction ID because of SSL secure connection issues? If so, then you should upgrade your server side environment to be able to support TLS v1.2 to make the call there. See the [PayPal TLS update site](https://github.com/paypal/TLS-update) for more information.
