### ISSUE TITLE
Can't pay using credit card

### ISSUE THREAD

**Issue by arifmc** [paypal/PayPal-iOS-SDK#128]
Hi, I'm using sdk 2.0.1 and I'm having issues with payment using credit card.

The card scanner works fine but when the customers press the "Charge Card" button, they got message saying that the merchant doesn't accept payment of this type like the one shown by the image.

![photo 2](https://cloud.githubusercontent.com/assets/3960207/2611624/1a4e82de-bba9-11e3-89b5-a4903befc787.PNG)

But if they pay via the website using the credit card it works fine. This is the debug id and error message that I got : 

PayPal SDK: Request has failed with error: UNAUTHORIZED_PAYMENT - The merchant does not accept payments of this type. (401) | PayPal Debug-ID: 1dcef154b15e4

One of our customer using New Zealand visa credit card crashed when he press the "Charge card button"

**Comment by rdmpris** [comment]
Were you able to fix this? @sevenb

**Comment by BeingHumanhelper5** [comment]
To make the CC payment work on paypal you need to upgrade your merchant/business account to PRO type.

**Comment by europa-promatics** [comment]
will it work with PRO account?

**Comment by bluk** [comment]
@europa-promatics Direct Credit Card (DCC) payments are deprecated in this SDK. Please use [Braintree Payments](https://www.braintreepayments.com/), a PayPal service, which is the easiest way to accept PayPal, credit cards, and many other payment methods.

I am locking this thread as this issue is not entirely applicable to the latest versions of the SDK.
