### ISSUE TITLE
Touch ID integration for PayPal SDK

### ISSUE THREAD

**Issue by jmbrenna** [paypal/PayPal-iOS-SDK#228]
Is there any plan to implement Touch ID in the PayPal SDK?  I saw that BrainTree has integrated it already, which is part of PayPal now, but this SDK is still missing that feature.  Any chance it will be implemented soon?

**Comment by bluk** [comment]
Closing this due to unlikely support for Touch ID in this SDK. If you need a faster experience with Touch ID, you can try using the Braintree v.zero SDK iOS integration. It supports One Touch which will allow for a much faster authentication method (either using the browser to automatically login or using the PayPal (Wallet) app which supports Touch ID to login).
