### ISSUE TITLE
How to void the transaction from the app side?

### ISSUE THREAD

**Issue by keenan16** [paypal/PayPal-iOS-SDK#253]
We create a PayPalPayment using PayPalPaymentIntentAuthorize intent. Our process is we get the authorize id, then we will pass that id to our server for capture. But when our server is unreachable is there's a way to void the transaction from the app side?

**Comment by romk1n** [comment]
@keenan16 you can only void transaction from your server since public client is insecure. Have a look at [webhooks](https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/) if the server is unavailable PayPal will try to deliver the event. Once delivered you can act according to your policy. Also bare in mind Authorization expire after certain time.

**Comment by keenan16** [comment]
@romk1n  Thank you for the answer. We will implement this kind of process. thanks :)
