### ISSUE TITLE
Method PayPal\Api\Sale::getTransactionFee() does not exist

### ISSUE THREAD

**Issue by antonioreyna** [paypal/PayPal-iOS-SDK#260]
Hello I am trying to validate a payment, but now im getting this error.

Method PayPal\Api\Sale::getTransactionFee() does not exist

I used to validate all the payments without any problem just today it started, i havent changed any files.

What could be happening?

Thanks

**Comment by dgoldman-ebay** [comment]
@antonioreyna could you please provide an extract from your console log, showing the error message in context?

**Comment by dgoldman-ebay** [comment]
@antonioreyna since this error is apparently happening on your server, rather than in the PayPal iOS SDK, could you please contact PayPal developer support to pursue this issue?

**Comment by jaypatel512** [comment]
Hey @antonioreyna ! The issue you are seeing is on the server code that you have hosted. It is actually caused by the new Payment API release done recently causing the SDK to break because of one forward-compatibility issue. We have already recognized the issue, and resolved it already. 

The [latest release v1.2.1](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.2.1) has the fix for this issue. Please update your server SDK to latest version, and you should be able to get it working. Apologies for the inconvenience. We couldn't realize this bug before it happened yesterday. 

Let me know if you run into any issues updating your Server SDK, and I would be happy to help resolve any issue. Feel free to create a new issue on [PayPal-PHP-SDK](https://github.com/paypal/PayPal-PHP-SDK)

Duplicate of https://github.com/paypal/PayPal-PHP-SDK/issues/255

**Comment by antonioreyna** [comment]
hello @dgoldman-ebay how can i check that log? is it possible to make it via curl or something? i am using laravel and the problem is on this line 

`$payment = Payment::get( $payment_id, $apiContext );`

**Comment by dgoldman-ebay** [comment]
@antonioreyna please ignore my previous comments (which I have now deleted). The answer from @jaypatel512 is the relevant answer.

**Comment by antonioreyna** [comment]
yes now im checking it thank you, ill let you know if everything is ok after the update thanks!

**Comment by jaypatel512** [comment]
Thanks @antonioreyna !

**Comment by antonioreyna** [comment]
everything seems to be working now thank you so much for your fast support!!

**Comment by jaypatel512** [comment]
Happy to help :)
