### ISSUE TITLE
"Unauthorized Payment" error with valid credit card in Live environment

### ISSUE THREAD

**Issue by atisman89** [paypal/PayPal-iOS-SDK#28]
We are done with testing iOS SDK in sandbox and are now testing payment in live environment for our iOS app. We are using SDK version 1.1.1 and used the live client ID retrieved from the app development site associated with our PayPal business account. Payment goes through without a problem when paid from a PayPal account but the credit card payment using "Pay with Card" feature doesn't seem to work. With a valid credit card information entered, we are having an error "Unauthorized Payment" and I have no clue on why we receive this error only with the credit card payment. Please refer to the following error message below. Any help will be appreciated.

![error](https://f.cloud.github.com/assets/5201302/942101/7080335c-0176-11e3-9c84-7dbda3aefc6d.png)

**Comment by wpspamhammer** [comment]
For anyone else that runs into this unfortunate "Unauthorized payment" problem, and does not see the appropriate permission in the developer site enabled, I got it enabled, and this is how:

1. If you are OUTSIDE the U.S., you need to have Payments Pro.
2. If you are INSIDE the U.S. (like us), you need approval for "PayPal Here" (that's the literal name)

The reason you need to be approved for "PayPal Here" in the U.S. (or "Payments Pro" elsewhere) to accept direct payment via the REST API is because that's what the API uses to capture payments.

For that are unaware of "PayPal Here", it's the service for U.S. account holders that lets you swipe credit cards with your smartphone using a small triangular card reader that PayPal mails to you.

The reason PayPal requires "Paypal Here" instead of "Payments Pro" for U.S. account holders is because the small card reader run on the same REST API you and I use from PayPal's Dev site.

The Payments Pro application process can be daunting because of the risk PayPal takes, and if mobile readers required that process, it could slow adoption of these devices significantly.

So, "PayPal Here" uses as a sort of middle ground between "Standard Payments" and "Payments Pro"/Virtual Terminal, without the drawn out Payments Pro application process.

So, when you click the "Enable live transactions" for the "Direct credit cards" API permission, and are sent to a page asking to verify your business information, it's not what it appears to be.

In reality, it's a "PayPal Here" application for U.S. account holders, and a "Payments Pro" application for non U.S. account holders.  The merchant team then looks it over, and approves or denies it.

This application page has bugs, like not sending the application to the merchant team, or redirecting you to the homepage with no reason.  This is frustrating, because non tech staff doesn't understand.

After contacting merchant technical support at http://www.paypal.com/mts and many exchanges to identify the core problem, they turned on "PayPal Here" and the REST API permission now works.

I hope someone else who is going through this frustrating process can get to the "other side" much quicker, without as much trouble and time.

**Comment by dgoldman-ebay** [comment]
Thanks, @wpspamhammer, for your detailed report!

**Comment by antypang** [comment]
@wpspamhammer, thanks for your explanation，very helpful. It seems card payment nothing to do with us now.

**Comment by wpspamhammer** [comment]
@antypang It's still possible to use PayPal card payments if you're in other countries, albeit indirectly; you can partner with a U.S. "host" business who has incorporated to create a PayPal account for you.

PayPal provides a facility to add additional users to accounts and it's perfectly legal to add someone in another country, so long as the host complies with the corporate laws and formalities in the U.S.

I called PayPal and asked if this was okay and they said it's legitimate so long as the laws and terms are followed.  We are reviewing partners right now, so if you are interested, send me a message.

**Comment by ppmtscory** [comment]
@wpspamhammer can you let me know your ticket number that you had with MTS?  I'd be curious to see the issue and how it was resolved by the addition of PayPal Here.  Adding PayPal Here to an account shouldn't have anything to do with processing direct credit cards with the mSDK.

**Comment by wpspamhammer** [comment]
@ppmtscory I don't have the ticket number anymore, it's been ~5 months.  As I noted earlier, even at MTS, many people weren't informed at all on this Here/Payments Pro tie in with the DCC permission.

The relation this has to the mSDK is that the mSDK uses the same REST API to capture card payments.

**Comment by antypang** [comment]
@wpspamhammer  This is an effective solution, but this in our company which deal with some difficulties, because it involves finances.  Btw, we use our credit card web receive payments in various regions are possible, now that the IOS client does not work, it is estimated that the interface is associated with the PP braintree.Anyway, thank you very much.

**Comment by ppmtscory** [comment]
@wpspamhammer thanks for checking.  I was going to use it as a training opportunity but I can send just a general note so that everyone is on the same page.  That page being that PPH enablement is not needed to do DCC with mSDK in supported countries.  If you happen to stumble across an old email with the ticket feel free to let me know.  Have a great day!

**Comment by wpspamhammer** [comment]
@ppmtscory While setting up another business account, I again ran into the same thing.  An approval, plus addition of paypal here, fixed the problem.  It appears the information you were provided is incorrect.

**Comment by ppmtscory** [comment]
@wpspamhammer while adding that product may work as a workaround for allowing DCC (due to the internal naming of the product), it is definitely not the correct way.  Also, since that's not correct, it's possible you may have unintended issues in the future if something should change with the internal product naming.  I'd love to know your new account where you went through this so that I can take a look and also talk with the agent that helped.

**Comment by vbresults** [comment]
--- forwarded from my deleted account ---

For anyone else that runs into this unfortunate "Unauthorized payment" problem, and does not see the appropriate permission in the developer site enabled, I got it enabled, and below I explain how.

1. If you are INSIDE the U.S. you need approval for "PayPal Here" (that's the literal name)
2. If you are INSIDE U.K. you need to have "PayPal Payments Pro"
3. If you are in neither the U.S. or U.K., you don't get the "Direct credit cards" permission.

The reason you need to be approved for "PayPal Here" in the U.S. (or "Payments Pro" elsewhere) to accept direct card payments via the REST API is because that's how the API captures payments.

"PayPal Here" is a the service for U.S. sellers that lets them swipe credit cards with their smartphones using a small triangular card reader that PayPal mails to them.

The reason PayPal requires "Paypal Here" instead of "Payments Pro" for U.S. account holders is because the small card reader uses the same REST API developers do to capture payments.

The Payments Pro application process can be daunting because of the risk PayPal takes, and if mobile readers required that process, it could slow adoption of these devices significantly.

So, "PayPal Here" sits on a card capture middleground between "Standard Payments" and "Payments Pro" that takes away the "Pro" application process while limiting PayPal's risk simultaneously.

So, when you click the "Enable live transactions" link for the "Direct credit cards" API permission, and are sent to a page asking to verify your business information, there is more than meets the eye.

In reality, it's a "PayPal Here" application for U.S. account holders, and a "Payments Pro" application for non U.S. account holders.  The merchant team then looks it over, and approves or denies it.

This application page has bugs, like not sending the application to the merchant team, or redirecting you to the homepage with no reason.  This is frustrating, because non tech staff doesn't understand.

After contacting merchant technical support at http://www.paypal.com/mts and many exchanges to identify the core problem, they turned on "PayPal Here" for me and the REST API permission now works.

I hope someone else who is going through this frustrating process can get to the "other side" much quicker, without as much trouble and time.

4/17/15 update: it seems Canada is no longer on the list of supported countries for direct credit card payments, so I've removed it.

4/28/15 It's still possible to use PayPal card payments if you're in other countries, albeit with help; you can partner with a U.S. "host" business who has incorporated and made a PayPal account for you.

PayPal provides a facility to add additional users to accounts and it's perfectly legal to add you, in another country, so long as the host complies with the corporate laws and formalities in the U.S.

I called PayPal and asked if this was okay and they said it's legitimate so long as the laws and terms are followed.

**Comment by deepaliVats** [comment]
hi
Whenever i have test it on sendbox its working properly.
 I have to face this error with credit card payment on live : 

{"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT","debug_id":"4bc820e1ef4f"}

To resolve it i haveto click on account eligibility.
but i dont know how to enable debit card.it show me enable as it is on live. 
what can i do to resolve that issue please quick response.

**Comment by bluk** [comment]
@deepaliVats Please contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com) for issues with your account.

**Comment by vbresults** [comment]
@deepaliVats See my message above.  If you are outside the U.S. and U.K., you can't use the REST API to capture card payments.

**Comment by deepaliVats** [comment]
Thanks for the reply bluk and vbresults.
yes i have to call paypal and they said that direct credit card not possible for rather than uk and us.

**Comment by santiagobenini** [comment]
@dgoldman-ebay can you tell if it's possible to accept payments mainly from foreigner's cards with a US company account? trough PayPal of course. It has to be a Pro account? we must apply to it?

**Comment by bluk** [comment]
@santiagobenini Please contact [PayPal support](https://www.paypal.com/us/selfhelp/home) for these types of questions. Thanks.
