### ISSUE TITLE
Return specific user displayable error messages

### ISSUE THREAD

**Issue by vineetmrug** [paypal/PayPal-iOS-SDK#308]
Hi, I just wanted to know, if my payment was not processable, is there any way to know, from within my code, the reason for this? I know that the reason gets logged onto the console, but it would be handy to be able to access the specific reason, so the user might be made aware of it through an alert or something similar. Thanks, and I look forward to your reply.

**Comment by tomwhipple** [comment]
A common source of problems in testing is to use the same account for both payer & payee.

Otherwise I'd suggest that you contact [merchant support](https://www.paypal.com/mts) with the debug ID that's printed in the console log. The support team has the ability to look up debug information and check your account settings.

However the detailed error string displayed in the log is not intended for user display.

**Comment by ladylo50bear** [comment]
Delete

**Comment by ladylo50bear** [comment]
Delete

**Comment by ladylo50bear** [comment]
Delete

**Comment by bluk** [comment]
Please contact [Merchant Technical Support](https://www.paypal-techsupport.com) for error specifics. Due to the wide variety of possible errors (and any new error that might occur) with little that the consumer can take action on, a generic error message is the best right now as a catch-all (instead of just letting the error message fall all the way through to the consumer). If there's a common error that the user can take action on, we will try to add error messages for them.
