### ISSUE TITLE
System error. Please try again later. (400)

### ISSUE THREAD

**Issue by devlonworks** [paypal/PayPal-iOS-SDK#315]
In ios everytime i am getting this error .
PayPal SDK: Request has failed with error: UNKNOWN_ERROR - System error. Please try again later. (400) | PayPal Debug-ID: 9cc195909af28 [sandbox, PayPal iOS SDK 2.11.4]

**Comment by tomwhipple** [comment]
Sandbox seems to be working for me now...

**Comment by tomwhipple** [comment]
In general, we the merchant support team can examine what is happening on the backend in both live and sandbox if you [contact them](https://www.paypal-techsupport.com/app/ask) and supply the `debug-id` that you've shared here.

But since the problem is no longer happening I am going to close this issue.

**Comment by Srikanth-Codebees** [comment]
Hi, can you help me with the same issue
PayPal SDK: Request has failed with error: UNKNOWN_ERROR - System error. Please try again later. (400) | PayPal Debug-ID: a9c4884c870cc

**Comment by xiaoleih41** [comment]
Please contact PayPal merchant tech support team at https://www.paypal-techsupport.com/app/ask regarding this issue. Thanks, Xiaolei
