### ISSUE TITLE
System Error in login/logout

### ISSUE THREAD

**Issue by baraabourghli** [paypal/PayPal-iOS-SDK#316]
Not a consistent error. ~~On manual testing login/logout works~~ when doing manual testing or Appium automated testing it fail to login/log out sometimes, showing the following error:
![screenshot_203909_ko](https://cloud.githubusercontent.com/assets/2780832/9650239/d4298458-5232-11e5-91a6-fbdcf7cea799.png)

this is happening in sandbox for now, we don't know if it happened in live.

Simulator: iPhone 5s
OS: iOS 8.4

It happened also in a real device: iPhone 5s
OS: iOS 8.2

**Comment by tomwhipple** [comment]
Sandbox is know to have occasional failures. In order to address them, you'll want to capture debug-id information printed in the XCode console log and [open an issue with PayPal merchant support](https://www.paypal-techsupport.com/app/ask/). They have the capability to track down those ID's individually.
