### ISSUE TITLE
When iOS9 payment system prompt:“We're Sorry System error.Please try again later. ”

### ISSUE THREAD

**Issue by Lorin331** [paypal/PayPal-iOS-SDK#331]
By iOS9 language resource identification is not the same impact in the Simplified Chinese system fails to identify the correct default display English interface, resulting in the failure to pay.
Alert:
We're Sorry
System error.Please try again later.

It has actually paid a success, no callbacks.

The system is switched to the English system, the payment is normal.

**Comment by tomwhipple** [comment]
Can you share the XCode log when this happens? Specifically I'm looking for a debug-id from the error message.

**Comment by Lorin331** [comment]
PayPal SDK: Request has failed with error: pp_service_error_empty_response - System error. Please try again later. (500) | PayPal Debug-ID: 16c67f39d586d [sandbox, PayPal iOS SDK 2.11.5]

**Comment by ppmtscory** [comment]
@Lorin331 it looks as if you are passing the incorrect locale in the SDK.  What I see from that debug ID is that the locale is zh-Hans-US instead of zh-Hans_US.  Notice the hyphen instead of underscore prior to the 'US'.  As a secondary answer, please be sure to check [this link](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/#direct-credit-card-payments) for the supported countries for credit card payments.

**Comment by Lorin331** [comment]
I found a solution:
Replaced by [[NSBundle mainBundle] preferredLocalizations]
[NSLocale preferredLanguages]

m_paypalConfig.languageOrLocale = [[[NSBundle mainBundle] preferredLocalizations] firstObject]; // [NSLocale preferredLanguages] [0];
