### ISSUE TITLE
Podspec for 2.12.2 not pushed?

### ISSUE THREAD

**Issue by kkarayannis** [paypal/PayPal-iOS-SDK#336]
I see version 2.12.2 on GitHub but CocoaPods say that it can't satisfy dependency. Doing a search on cocoapods.com only brings up 2.12.1

**Comment by kkarayannis** [comment]
Also pointing directly to the GitHub url in my podfile, it seems like the card.io library is missing from the podspec.

**Comment by bluk** [comment]
@kkarayannis You are right. I believe CocoaPods can't pick it up during `pod install` because the libCardIO.a is currently zipped in the repository (due to [GitHub file limits](https://help.github.com/articles/working-with-large-files/) we can't just push the library up ). I am investigating alternatives to the distribution or if we can trim the library. Thanks for your investigation.

I don't recommend it for the long term but you might be able to manually unzip the `libCardIO.a.zip` and put it in the correct directory.

**Comment by kkarayannis** [comment]
I was going to do that, but I saw that card.io is 90MB (zipped!) and PayPal itself is another 50. Is this bloat because of Bitcode? If that's the case, as Apple's app slicing is currently [disabled](https://developer.apple.com/news/?id=092415a&1443125762), it might be a good idea to hold it back for a bit longer, at least until Apple enables App Thinning again.

**Comment by bluk** [comment]
Yes, it is mainly due to Bitcode enablement. There were some internal changes to make `libPayPalMobile.a` to be weakly linked to `libCardIO.a` but nothing significant. One of my todos is to investigate if there are options to slim the static library down (maybe not Bitcode embed the x86_64 portion of the library for iOS) but I think more people are interested in having Bitcode enabled for their application.

Your final application delivered to users should not be significantly larger after the Bitcode enabled app is recompiled and optimized on Apple's servers. I would imagine that Apple can still re-compile the executables (even if into a universal app without app slicing), but I could be mistaken. If someone has more knowledge, please feel free to share.

**Comment by jeremylan** [comment]
Any updates on this? It's quite a scary issue just reading the comments with the libcardio zipped and the huge size of the libraries
Thanks

**Comment by bluk** [comment]
@jeremylan Still looking into this (maybe use the [prepare_command](http://guides.cocoapods.org/syntax/podspec.html#prepare_command) to unzip the library before install).

You can test how big your overall application will be after Bitcode is fully enabled in your app by doing a local Ad Hoc or Developer release. It should "bit code compile" locally. In local testing, I didn't see the app size become bigger but please open an issue or leave a comment if you have a different experience.

To test:

1. Archive your application.
2. Go to the Xcode Organizer (from Window > Organizer)
3. Find the Archive and click Export.
4. Click the Ad Hoc Deployment or Development Deployment.
5. Choose whether or not you want to create a Universal Version or an App Thinned version. As @kkarayannis noted, App Thinning is currently disabled so you may want to just choose `Export one app for all compatible devices`.
6. In the Summary step, be sure to check `Export from bitcode` to simulate how the App Store would build your app. The `Learn More` link has more details.

**Comment by jeremylan** [comment]
@bluk thanks for the tips, I'll try out

**Comment by bluk** [comment]
@kkarayannis We pushed out version 2.12.3 to help fix the CocoaPods issue. The libraries are still the same size but the CocoaPods itself should unzip the `libCardIO.a.zip` and the Pods should resolve the `libCardIO.a` dependency. I'll continue investigating if we can reduce the size of the library. If the CocoaPods still can't work, please reopen. Thanks!
