### ISSUE TITLE
Why is the SDK so large?

### ISSUE THREAD

**Issue by MattFoley** [paypal/PayPal-iOS-SDK#349]
PayPal is currently the largest SDK we link into our binary. As an SDK ourselves, which only support a single transaction, we would much prefer a smaller, more streamlined SDK. The PayPal SDK adds at least 5mbs to our binary. 

Is a smaller SDK possible? Why is it so large? Are there any other options for making it smaller?

**Comment by bluk** [comment]
@MattFoley If you only need to support `Login with PayPal` flows, you can try using just the `libPayPalMobile.a`. The sample apps included in this repository have different targets showing the differences between just having `libPayPalMobile.a` vs. having both `libPayPalMobile.a` and `libCardIO.a` included. The static library files are large due to Bitcode, but I assume you're talking about the final binaries being produced.

**Comment by MattFoley** [comment]
I'm not using libCardIO.
