### ISSUE TITLE
Future Payment is not returning authorization code

### ISSUE THREAD

**Issue by ravifullestop** [paypal/PayPal-iOS-SDK#354]
I have successfully integrated future payment function in my application to test with sandbox enviourment but this is returning below response

[client: {
    environment = mock;
    "paypal_sdk_version" = "2.11.4";
    platform = iOS;
    "product_name" = "PayPal iOS SDK";
}, response_type: authorization_code, response: {
    code = AuthorizationCodeForNoNetworkEnvironment;
}]

It should give me a valid authorization_code rather than AuthorizationCodeForNoNetworkEnvironment

Please help

**Comment by ppmtscory** [comment]
@ravifullestop according to your response, you are using the "mock" environment so this is the expected resolution.  The mock environment simply runs through the motions with standard data.  You need to be sure that all instances of your app are using PaypalEnvironmentSandbox instead of PayPalEnvironmentNoNetwork.
