### ISSUE TITLE
credit card is not working

### ISSUE THREAD

**Issue by harshad89** [paypal/PayPal-iOS-SDK#372]
when i press payment via credit card then it is crashed and give lldb error only nothing else..

how to solve it i used your latest sdk

**Comment by bluk** [comment]
Which version of the SDK are you using? [2.12.9](https://github.com/paypal/PayPal-iOS-SDK/releases) is the latest release and depending on which version you were using, there were different fixes made to the credit card flow over the last few months.

**Comment by harshad89** [comment]
yes in 2.12.9 version

**Comment by harshad89** [comment]
please can you solve this in your latest sdk?

**Comment by bluk** [comment]
Does the sample application work?

Also are there any additional details you can provide? Such as iOS version, device you are using, locale of the device? I'm having difficulty reproducing your issue without additional details. Thanks.

**Comment by harshad89** [comment]
sample application also doent work

**Comment by bluk** [comment]
What are your language/locale settings (English/US or something else)? Also, is there any information via Xcode (like a backtrace or any other specific error)?

I tried on a couple of iOS 9.2 devices (iPhone 5 and iPhone 6 Plus) and they opened up the credit card scanning view correctly so I'm thinking there's some specific combination of locale settings or some specific code that is causing an issue.

**Comment by harshad89** [comment]
english us langauge i am using .. and there is no any information via excode just lldb
credit card view .. where we can enter details of it

**Comment by harshad89** [comment]
this is my code and we use latest sdk with xcode 7.2 and ios 9.2(13c75)
(void)paypalPurchase {
    PayPalPayment *payment = [[PayPalPayment alloc] init];
        payment.amount = [[NSDecimalNumber alloc] initWithString:[NSString stringWithFormat:@"%.2f",total]];
    
    payment.currencyCode = @"USD";
   
        payment.shortDescription = [_Info objectForKey:kTitleKey];
    
    if (!payment.processable) {
        NSLog(@"not processable");
    }
    PayPalConfiguration *paypalConfig = [[PayPalConfiguration alloc] init];    
    paypalConfig.acceptCreditCards = YES;
    
    
    paymentViewController = [[PayPalPaymentViewController alloc] initWithPayment:payment
                                                                   configuration:paypalConfig
                                                                        delegate:self];
    
    [self presentViewController:paymentViewController animated:YES completion:nil];

**Comment by harshad89** [comment]
ibc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

this bugs i got in your example

**Comment by bluk** [comment]
Are you running the `PayPal-iOS-SDK+cardio-Sample-App` target (not the `PayPal-iOS-SDK-Sample-App` target)? The sample should run without any modification with that target to be able to scan credit cards.

Also, are you linking the card.io static libraries in your app?

I assume that `ibc++abi.dylib` is actually `libc++abi.dylib`. Usually there is more information before this. Something like

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <PayPalPaymentViewController: 0x12f068a00
Environment: mock
languageOrLocale: en-US
>
```
would indicate that the libraries are not all correctly included.

**Comment by hakimny** [comment]
Hi there,

Make sure you are running PayPal-iOS-SDK+cardio-Sample-App Taget, i got similar errors when I tried the PayPal-iOS-SDK-Sample-App and turned self.payPalConfig.acceptCreditCards to true. I did not realized there were actually 2 targets on that sample app.

thx

**Comment by sambitantech** [comment]
Hi,

I am using paypal 2.14.1 SDK for iOS.That SDK working fine for ipad. When am running same code in iphone,camera view not opening

**Comment by bluk** [comment]
@sambitantech Have you given given camera permissions for the sample app? If you're unsure, can you check the Settings app and look for the Sample App's permissions. Thanks.

**Comment by sambitantech** [comment]
@bluk in my project camera view is open for ipad. when i am running same code for iphone camera view not open.

**Comment by bluk** [comment]
@sambitantech I would try to run the sample code project and use the `PayPal-iOS-SDK+cardio-Sample-App` target (not the `PayPal-iOS-SDK-Sample-App` target) to see if the SDK works first and see if you get a camera permission dialog box.

In previous similar issues, it was either because the app was not granted camera permissions or there was a rare instance of an iOS bug where the permission never presented itself. You can check the Camera Permissions in the Settings app (`Settings > Privacy > Camera` or `Settings > (Your app)`). If the permission is not present on those pages and you're sure your code was executed, on a test device, you can try `Settings > General > Reset` and then `Reset Location & Privacy` (note this resets several privacy settings but others have seen the setting re-appear).

**Comment by amitdagar** [comment]
![screen shot 2017-04-22 at 2 14 52 pm](https://cloud.githubusercontent.com/assets/16076453/25302894/229ec8f0-2766-11e7-80e8-f15b2c0bb2d5.png)

I did not find any  `PayPal-iOS-SDK-Sample-App` in the latest paypal-sdk 2.17.0

**Comment by bluk** [comment]
@amitdagar I'm assuming you mean you cannot find the `PayPal-iOS-SDK+cardio-Sample-App` target in the [`PayPal-iOS-SDK-Sample-App`](https://github.com/paypal/PayPal-iOS-SDK/tree/master/SampleApp). As of release [2.16.0](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.16.0), credit card usage in this SDK has been deprecated, and the sample was changed to discourage usage of it. Especially note that [Direct Credit Card support](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/#direct-credit-card-payments) is only supported with specific merchant accounts in the REST API which this SDK uses. It is strongly recommended that you use [Braintree Payments](https://www.braintreepayments.com), a PayPal service, to perform credit card processing which has support for more countries.

If you use this SDK for credit card processing, you can check out version 2.15.1 and see the sample app as an example on [how to setup card.io with the SDK](https://github.com/paypal/PayPal-iOS-SDK/tree/2.15.1#if-you-dont-use-cocoapods-then). The major difference is that the card.io libraries path is added to the `Library Search Path` in the Build Settings and the card.io libraries are added to the `Link Binary with Libraries` Build Phases.

I'll leave a similar comment in https://github.com/paypal/PayPal-iOS-SDK/issues/524 which you opened and can continue the discussion there since it seems directly related.
