### ISSUE TITLE
shipping address not valid? setup receiverEmail?

### ISSUE THREAD

**Issue by blackmatch** [paypal/PayPal-iOS-SDK#375]
hello,
when I use PayPal-iOS-SDK in sandbox environment. I setup a shipping address like this:
PayPalShippingAddress *shippingAddress =  [PayPalShippingAddress shippingAddressWithRecipientName:@"blackmatch" withLine1:@"minhang district" withLine2:@"jiangchuan road No.955" withCity:@"shanghai" withState:@"China" withPostalCode:@"201100" withCountryCode:@"86"];
    payment.shippingAddress = shippingAddress;

but when I click the "pay" button , there is a alertView showing:We're sorry. The provided shipping address is not valid. Who can tell me how to setup the shipping address correctly.

In fact, I just want to pay to  a business paypal account. I think I just need to setup the receiverEmail. It's no need to setup the shipping address. But I have no idea to setup the receiverEmail using the newest SDK(2.12.9). I cannot find the new API method. How can I do this?

**Comment by bluk** [comment]
For the shipping address, you can set your `PayPalConfiguration.payPalShippingAddressOption` to be `PayPalShippingAddressOptionNone` if shipping does not apply.

The receiver of the payments is determined by the client ID you set. See the [sample app code](https://github.com/paypal/PayPal-iOS-SDK/blob/master/SampleApp/PayPal-iOS-SDK-Sample-App/ZZAppDelegate.m#L17). You do not set a receiverEmail.

BTW, I believe the reason why your shipping address is incorrect is because the state value should not be China.

**Comment by blackmatch** [comment]
Thank you for your help! Now, I can complete the payment in the sandbox environment. But there is still a question. If I want to use  a business account for receiving payment account, should I must setup the business account to be developer account, and then apply the client ID, and use the  given client ID in my project? I want to get the client ID use my personal paypal account(developer account), and use another business account as the receive payment account. How can I do this?

**Comment by bluk** [comment]
You should use the client ID of the merchant/business account that would receive the payments (e.g. setup the business account to be a "developer" account). Is there a reason why you want to use the clientID of your personal account?
