### ISSUE TITLE
Request has failed with error: UNAUTHORIZED_PAYMENT 

### ISSUE THREAD

**Issue by pradipstripe** [paypal/PayPal-iOS-SDK#393]
i work with paypal  SDK 2.12.3 when i try  with PayPalEnvironmentProduction mode with live client id then  getting error like

paypal business  Account is under  Australia  country. 
 
PayPal SDK: Request has failed with error: UNAUTHORIZED_PAYMENT - The merchant does not accept payments of this type. (401) | PayPal Debug-ID: 7aafbfa496631, 7aafbfa496631 [live, PayPal iOS SDK 2.12.3]
 
any help appreciate

**Comment by bluk** [comment]
@pradipstripe "You are getting that message because you are attempting to process direct credit card payments with a merchant account registered in a country where it's not available. Direct Credit Card transactions with the mSDK (and REST API in general) is available in US and UK only."

See https://github.com/paypal/PayPal-Android-SDK/issues/224#issuecomment-162927517

**Comment by MandalAkash** [comment]
I am using PayPal iOS SDK Version: PayPal iOS SDK 2.17.0 and when i try with PayPalEnvironmentSandbox mode with sandbox client id and also PayPalEnvironmentPrdouction mode with live client id then getting error like
PayPal SDK: Request has failed with error: UNAUTHORIZED_PAYMENT - The merchant does not accept payments of this type. (401) | PayPal Debug-ID: d1cb2eee43dac, d1cb2eee43dac [live, PayPal iOS SDK 2.17.0] i used US paypal account and USD Currency.
