### ISSUE TITLE
Internal Service Error

### ISSUE THREAD

**Issue by martylongdsi** [paypal/PayPal-iOS-SDK#412]
Trying to access PayPal using the iOS SDK, but am getting the following error.

"We're Sorry: There was a problem communicating with the PayPal servers. Please try again."

I'm seeing an INTERNAL SERVICE ERROR in the logs:

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: aa1bcff5904a5, aa1bcff5904a5 [sandbox, PayPal iOS SDK 2.5.0]

Can't find anything else online about the Sandbox being down.

**Comment by ppmtscory** [comment]
Hi all, sandbox appears to be experiencing some downtime. We're tracking the issue over at [paypal/PayPal-PHP-SDK#531](https://github.com/paypal/PayPal-PHP-SDK/issues/531), so I'm going to close this one as a duplicate so that we don't have multiple threads. We'll provide back information as we can there.
