### ISSUE TITLE
PayPal SDK: Request has failed with error: invalid_request - An error has occurred. (400)

### ISSUE THREAD

**Issue by ddferrando** [paypal/PayPal-iOS-SDK#425]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: 2.14.1
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): iPhone 6 iOS 9.3.1
- PayPal-Debug-ID(s) (from any logs): 936dda76329c

### Issue Description
Hi.
I am trying to implement a Paypal login to allow user tor introduce their account, a receive payments from my company. 
It's not needed in the app that user can make payments, just receive it.
The scope values that I am using are:
- kPayPalOAuth2ScopeFuturePayments
- kPayPalOAuth2ScopeProfile
- kPayPalOAuth2ScopeOpenId
- kPayPalOAuth2ScopeEmail

I am not clear, which App feature options I need to activate.
I hope this must be the problem, but I am not sure.
Thanks
David

**Comment by bluk** [comment]
Unfortunately, your use case isn't directly supported by this SDK. For payments, this SDK is intended to send payments to one merchant account. See https://github.com/paypal/PayPal-iOS-SDK/issues/9 which isn't in the near future.

That being said, you may try using the [Login with PayPal](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_server.md) flow as you are doing. You should be able to get an email associated with the PayPal account with just the `kPayPalOAuth2ScopeEmail` scope.

Then, you will probably have to look into [Adaptive Payments or Mass Payments](https://developer.paypal.com/docs/marketplace-split-payments/) depending on your use case.

Regarding the 400 in your request, I would double check that the client ID supplied is correct for the environment and that you have the [Log In With PayPal permission for your account on the developer dashboard](https://developer.paypal.com/developer/accountStatus/).

Hope that helps. If you have another question, please leave a comment and we'll reopen or open a new issue. Thanks!

**Comment by ddferrando** [comment]
Yes, basically what we want is to get the user email associated with a PayPal account.
Then, in the back end we will implement a way to pay to the users.
So, what I made it's not to include the scope for kPayPalOAuth2ScopeFuturePayments.
But now I am having this error.

> Error Domain=ApiError Code=500 "Unable to connect to paypal" UserInfo={NSLocalizedDescription=Unable to connect to paypal}

Just one question.
I read that for sandbox paypal we need minimum suport for TLS v1.2, but for production it's enough with TLS v1.0. It's that true?
Because our server don't support TLS v1.2.
Could be this the reason why we can not Login with Paypal?
Thanks

**Comment by bluk** [comment]
@ddferrando Yes, TLS v1.2 is required for sandbox. It is part of a broader payment industry requirement. You can find out some more info and links at the [TLS-update repository](https://github.com/paypal/TLS-update). The production server will require TLS v1.2 in the future. It isn't required right now in order to give time for people to upgrade. Please see the site for more info and links to pages with relevant dates.

I'm not sure if you're running into a TLS issue given the error that you posted, but it could be possible (and if not, you will run into that error later). I assume the error you posted is coming back from your server, and your server could be giving a 500 response to your client when it can't connect to PayPal. Regardless, you will need to update to a TLS 1.2 compatible web stack, and I would do it before putting anything into production.
