### ISSUE TITLE
it does not check user account exist  or not at login time

### ISSUE THREAD

**Issue by anirudhsmarttechnica** [paypal/PayPal-iOS-SDK#428]
### Required Information

- Mode (Mock/Sandbox/Live):
- PayPal iOS SDK Version:
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

**Comment by bluk** [comment]
@anirudhsmarttechnica Are you running in `mock` mode? Mock does not verify the account existing since it makes no network calls, but if you use the sandbox or live modes, it will.

You can find out how to setup your environment in the [Sample Code doc section](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/single_payment.md#sample-code). Sandbox test accounts can be created via the [Developer Dashboard](https://developer.paypal.com/developer/accounts/) if you use that mode.

If you're still running into an issue, then please leave another comment and we'll reopen. Thanks!
