### ISSUE TITLE
Can't Pay With Card - "The Network Connection Was Lost"

### ISSUE THREAD

**Issue by glennposadas** [paypal/PayPal-iOS-SDK#435]
### Required Information

- Mode (Mock/Sandbox/Live): **Sandbox**
- PayPal iOS SDK Version: **sandbox, PayPal iOS SDK 2.14.2**
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): **iOS 9.3 iPhone 5 Simulator**
- PayPal-Debug-ID(s) (from any logs): **No debug logs**

### Issue Description
> The PayPal SDK works so fine when using a PayPal Account, but when I try to use Pay with card, I can't connect to the PayPal Server, and there is no debug logs, only this:

`2016-07-18 10:00:03.447 UPlant[23489:265771] NSScanner: nil string argument
2016-07-18 10:00:04.036 UPlant[23489:265771] Can't find keyplane that supports type 4 for keyboard iPhone-Portrait-NumberPad; using 563160167_Portrait_iPhone-Simple-Pad_Default
2016-07-18 10:00:04.077 UPlant[23489:265771] NSScanner: nil string argument
2016-07-18 10:00:04.077 UPlant[23489:265771] NSScanner: nil string argument
2016-07-18 10:00:04.077 UPlant[23489:265771] NSScanner: nil string argument
2016-07-18 10:00:08.415 UPlant[23489:265771] Can't find keyplane that supports type 4 for keyboard iPhone-Portrait-NumberPad; using 563160167_Portrait_iPhone-Simple-Pad_Default
2016-07-18 10:00:10.070 UPlant[23489:265771] Can't find keyplane that supports type 4 for keyboard iPhone-Portrait-NumberPad; using 563160167_Portrait_iPhone-Simple-Pad_Default`

![screen shot 2016-07-18 at 10 00 43 am](https://cloud.githubusercontent.com/assets/12502679/16904788/a44c9be8-4cce-11e6-8b72-cba75b546de9.png)

additional info: Im from the Philippines, currency in my code is "USD". I input account number to the simulator: 4242 4242 4242 4242, 12/30, 333. Or should I use a real credit card for sandbox testing?

what might be wrong? -- side quick question: where can I find the details of the transaction? I mean the total amount, items, user details who paid the items???

**Comment by glennposadas** [comment]
anyone? @bluk  @tomwhipple

**Comment by glennposadas** [comment]
well, guess what? I just figured out that the common test card numbers shouldn't be used in sandbox testing. Thanks to this issue: [](https://github.com/paypal/PayPal-iOS-SDK/issues/102) ... It took me 11 hours before I solved this. I'll blog this in the future. :">

**Comment by Stakenborg** [comment]
I've been seeing this intermittently on 2.16.0. When it happens it created a pretty awful situation where the user was charged, but since we received an error back from the SDK, we never credited their account in the app. Big problem. Looks like 2.16.1 is 'Improve network code reliability.' so maybe this is known?

**Comment by bluk** [comment]
@Stakenborg 2.16.1 did change the networking code. In addition, I would recommend that you set an Invoice Number to help track payments and set authorize as [your intent](https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalPayment.h#L182) so you capture funds at a later time. You will need a server side process to capture the funds.

**Comment by Stakenborg** [comment]
Thanks for the response @bluk. We're going to look into solidifying as much as we can on our side. Thanks for the link too!

**Comment by Stakenborg** [comment]
I'd like to point out that we are still seeing this error in the 2.16.1 build, but with a different error message now. Again, still very intermittent, but still performing the charge while returning an error. This error appears to have begun after a pod update to 2.16.0, considering a rollback until this is resolved. We currently use auth intent for a different flow, so without a fairly significant rework, that is out.

This is the new message:

"We’re Sorry - There was a problem communicating with the PayPal servers. Please try again."

**Comment by Stakenborg** [comment]
An additional point here, we have noticed that even with Authorize as the intent there are issues related to this.

If the intent is Sale and we hit this issue, payment goes through to our account, but since the SDK did not return a payment to us, it does not get consumed by our back end.

If the intent is Authorize, payment is pending, but since the SDK does not return the payment to us, the back end has no concept of the authorization ever existing, so we can't void the payment after a period of time automatically.

Seems to me this should be reopened, or maybe even opened as a new issue itself. I can help provide some information in the form of examples to work on this if possible.

**Comment by jaypatel512** [comment]
Hey @Stakenborg !

you are absolutely correct. The issue is, if there are any network connection failures between mobile and server, it throws you this error. However, the server goes through with the payment. 

Can you please re-open a new issue, as this particular issue seems to be solving a different problem.

**Comment by Stakenborg** [comment]
Hey @jaypatel512

I probably will open a new issue about this soon, however on our sessions we've seen users have this error happen multiple times in a row while on wifi. Not sure what the exact cause is but it appears to be more than just a lost connection from what I've seen. We've since rolled back to 2.15.1 and haven't had this issue since.

Once I get to a computer (possibly after Thanksgiving weekend) I'll piece together an issue with all the info I have on it.
