### ISSUE TITLE
Carthage compatibility.

### ISSUE THREAD

**Issue by Dershowitz011** [paypal/PayPal-iOS-SDK#438]
Please make this library carthage compatibility. Much more easier to integrate into iOS projects. Thank you.

**Comment by bluk** [comment]
Please see the [PayPalMobileSDKFramework](https://github.com/paypal/PayPal-iOS-SDK/tree/master/PayPalMobileSDKFramework) directory for information on how to integrate with Carthage. If you still have an issue or encounter a problem with the integration, please leave another comment. Thanks.

(Note: Re-added the PayPalMobileSDKFramework directory due to a build script gone awry but this should hopefully get you started.)

**Comment by Dershowitz011** [comment]
I get this when I run `carthage update --platform iOS`. What do I do?

```
*** Checking out PayPal-iOS-SDK at "33e27f020b26fb0a5d2038e5c1046e0f7d5fd89d"
A shell task (/usr/bin/env git clone --quiet git@github.com:card-io/card.io-dmz.git%
```

**Comment by bluk** [comment]
@Dershowitz011 

Do you have a [SSH key added to your GitHub account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)? Having a SSH key should allow you to checkout via git ssh URLs.

If you don't want to use the SDK for credit card scanning, you can remove the card.io dependency in the Cartfile.

**Comment by Dershowitz011** [comment]
Perfect. It works. Thanks a lot. 👍

**Comment by Johennes** [comment]
Does that mean card.io only works on carthage if people have a GitHub account set up? I find that a little confusing because I can clone this repo just fine on the CLI without referencing my GitHub account at all. Yet, when I do it through Carthage, it fails with the error in #68.

**Comment by pp-randy** [comment]
If you clone a public repo and your link starts with`https://github.com` then you don't need an ssh key because its using https.  If you see `git@github.com` then it is trying with SSH and I believe you need an ssh key set up for that.
