### ISSUE TITLE
App store rejection due to private API usage. (setNavigationBarTintColor)

### ISSUE THREAD

**Issue by jasonblood** [paypal/PayPal-iOS-SDK#456]
### Required Information
- PayPal iOS SDK Version: 2.14.7

### Issue Description
So we just had a app store build rejected due to private API usage. The method in question was `setNavigationBarTintColor` I couldn't find any references to this method in my own code. So I ran the following command `grep -r setNavigationBarTintColor .`  in the root directory of the project. A match was found in libPayPalMobile.a

**Comment by bluk** [comment]
@jasonblood The PayPal iOS SDK calls this setter on the [Card.IO PaymentViewController](https://github.com/card-io/card.io-iOS-SDK/blob/master/CardIO/CardIOPaymentViewController.h#L59) which is a property of the Card.IO View Controller (not a private API). It's related to https://github.com/card-io/card.io-iOS-SDK/issues/201 . It seems there's a collision with some names with Apple's screening process from time to time. I would dispute this to improve Apple's process with this info since these are common names that will collide eventually.

**Comment by bluk** [comment]
Please try release [2.15.1](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.15.1) which should be calling a differently named method.

**Comment by jasonblood** [comment]
Great. Thanks for the help @bluk
