### ISSUE TITLE
PayPal SDK IOS: Request has failed with error: INSTRUMENT_DECLINED

### ISSUE THREAD

**Issue by angelicaib** [paypal/PayPal-iOS-SDK#463]
### Required Information

- Mode (Mock/Sandbox/Live): Live
- PayPal iOS SDK Version:[live, PayPal iOS SDK 2.14.2]
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): iOS 9.3 iPhone 5s
- PayPal-Debug-ID(s) (from any logs):323d010b95e6, 323d010b95e6

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.
I was testing with sandbox environment and everything is ok, no problems. 
Now, I change to production environment, I changed credentials too, but when I want to buy, I used two real accounts and appears this message: "PayPal SDK: Request has failed with error: INSTRUMENT_DECLINED - Your selected payment method was not accepted. Please choose a different method. (400) | PayPal Debug-ID: 323d010b95e6, 323d010b95e6 [live, PayPal iOS SDK 2.14.2]".
Am I missing something? Please some advices!! Thanks

**Comment by bluk** [comment]
Can you please check that your live PayPal accounts have valid credit/debit cards? The credit/debit account seems to be declined because it is invalid.

If that doesn't resolve your issue, please contact [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) who can help assist with live account issues.
