### ISSUE TITLE
Lump-sum payment to backend ID upload resources, has always been does not exist, what the hell?

### ISSUE THREAD

**Issue by 15038777234** [paypal/PayPal-iOS-SDK#483]
{"name":"INVALID_RESOURCE_ID","message":"Requested resource ID was not found.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INVALID_RESOURCE_ID","debug_id":"b503068595c45"}
![qq20161110-1](https://cloud.githubusercontent.com/assets/4713847/20168279/23953300-a75c-11e6-8fb2-08eb65d6070d.png)
![qq20161110-2](https://cloud.githubusercontent.com/assets/4713847/20168285/2b887356-a75c-11e6-95ce-df5b6ddee41d.png)

**Comment by bluk** [comment]
You seem to be in `mock` mode and trying to retrieve a payment ID with the value `PAY-NONETWORKPAYIDEXAMPLE123`. Please [preconnect](https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalMobile.h#L54) and use the `PayPalEnvironmentSandbox` environment instead of `PayPalEnvironmentNoNetwork`.

**Comment by 15038777234** [comment]
@bluk I give it a try.
