### ISSUE TITLE
Paypal iOS SDK do not work on card payment

### ISSUE THREAD

**Issue by nirob10** [paypal/PayPal-iOS-SDK#488]
- Mode: Sandbox
- PayPal iOS SDK Version: 2.12.4
- iOS Version and Device (iOS 10.x on each iPhone)
- PayPal-Debug-ID: 774508fe695b4

Paypal iOS SDK work fine when I pay from paypal but when I pay from debit/credit card then payment do not complete. It says in log "Request has failed with error: DUPLICATE_REQUEST_ID - System error."

**Comment by bluk** [comment]
Hi, the underlying error seems to indicate the domestic transaction is unsupported. Please ensure that [your account is supported for credit card transactions](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/). Usually this is because the sandbox merchant account is located in an unsupported country. For instance, if your merchant account is based in India, then direct credit card transactions are not supported for your country.

Also, please note that direct credit card support has been deprecated in this SDK as of the latest [version 2.16.0](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.16.0). I strongly suggest for any new integration to see if [Braintree Payments](https://www.braintreepayments.com) can support you. Please check if they support your country as well.
