### ISSUE TITLE
The Network Connection Was Lost

### ISSUE THREAD

**Issue by knutigro** [paypal/PayPal-iOS-SDK#489]
### Required Information

- Mode (Mock/Sandbox/Live): **Live**
- PayPal iOS SDK Version: **2.15.1**
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
Hi, 
We  get bug reports from our users claiming to receive error message ("The Network Connection Was Lost") when trying to verify their account using `PayPalProfileSharingViewController` Users say network is good for other calls except when connecting to PayPal. 

Issue might be related to : https://github.com/paypal/PayPal-iOS-SDK/issues/435

Greetings from Knut

**Comment by bluk** [comment]
Was this just in the last few hours or has this been a persistent issue?

**Comment by knutigro** [comment]
This happened a while ago. User reported that he received this message during several attpemts. it could be temporary problem, but when looking at the other issue i linked to , I wonder if could be  a problem within your library.

**Comment by teffi** [comment]
I'm experiencing the same issue for 2 days on sandbox v2.16.1 during login or payment (Order intent). It appears to be intermittent and not directly related to the device's network connection since I'm pretty sure I have a stable network. In addition, I sometimes get "Payer action required" instead of "Network Connection Lost" as an error. 

As described by @knutigro having read through previous issued ticket  this might be a library problem.

**Comment by darshana-ios** [comment]
We are experiencing this issue since last few days.

**Comment by ppmtscory** [comment]
As to not have account information in a public forum, can you folks please file a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team with email addresses of buyer/receiver accounts and specific date/time stamps (including time zone) of when these messages occurred?  We'll need to take a look into our logs internally and see if we can find anything causing the error.  I'll close this issue out as it will be handled through the tickets filed with specific account info.
