### ISSUE TITLE
Invalid user credentials

### ISSUE THREAD

**Issue by JokerHappy** [paypal/PayPal-iOS-SDK#491]
### Required Information

- Mode (Live):
- PayPal iOS SDK Version:2.14
- iOS Version and Device (iOS 9.2 on an iPhone 6s):
- PayPal-Debug-ID(s) (5090bcae50f99):

@bluk In my App use the correct account password login is invalid，however, in the paypal website can be normal landing.
I do not know where the problem is.

this is error log:

```
2016-12-02 12:30:14.113 Douou[18869:2107251] -canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "(null)"
2016-12-02 12:30:28.731 Douou[18869:2107251] PayPal SDK: Request has failed with error: invalid_user - Incorrect username/password. Please try again. (401) | PayPal Debug-ID: 5090bcae50f99, 5090bcae50f99 [live, PayPal iOS SDK 2.14.6] | Details: (
        {
        "error_description" = "Invalid user credentials";
    }
).
```

the info.plist show source code

```
		<string>org-appextension-feature-password-management</string>
		<string>com.paypal.ppclient.touch.v1</string>
		<string>com.paypal.ppclient.touch.v2</string>
```

thanks

**Comment by JokerHappy** [comment]
so i change PayPal iOS SDK Version to 2.16 , new issue appeared 

```
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: ea94a21198c0b, ea94a21198c0b [live, PayPal iOS SDK 2.16.1]
```

I had not modified any code，so  what's the problem ?

**Comment by JokerHappy** [comment]
I reference the demo to set the PayPal SDK. When I use my ID instead of the demo's client ID, the above problem will also happen .  
Can you give me the details step how to create app at the PayPal developer website?thanks

**Comment by bluk** [comment]
@JokerHappy From what I can tell in your `PAYMENT_CREATION_ERROR`, the payment was denied. Generally, I would check that your customer account is setup with valid funding instruments (e.g. bank account or credit card) and your merchant account is enabled for taking payments on [live production to take PayPal payments](https://developer.paypal.com/developer/accountStatus/) and try again. If you continue to get an error, you should contact [PayPal Support](https://www.paypal.com/us/selfhelp/home) since it seems that the error is particular to your account.

The README documentation has more info especially the [Next Steps](https://github.com/paypal/PayPal-iOS-SDK#next-steps) section.

Also, since this seems to be a new integration, you may want to check if the [PayPal Express Checkout with v.zero](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-vzero/get-started/) experience based on [Braintree Payments](https://www.braintreepayments.com) is also suitable.

If you still have additional questions, please leave a comment. Thanks.

**Comment by JokerHappy** [comment]
@bluk  Thanks
