### ISSUE TITLE
Buyer's Shipping Address Not Included

### ISSUE THREAD

**Issue by annca** [paypal/PayPal-iOS-SDK#50]
We've just implemented this library in our app to enable purchasing of physical goods.  However, once we ran a live test, we realized that the transaction receipt does not include the buyer's shipping address (even though the buyer has one verified on her account). Why is that? I've read that this may happen when payment is sent as a gift. Is this the default type of payment in this library? I don't see a way to specify it for "Goods". Could someone shed light on this? Thanks

**Comment by shabi** [comment]
I have integrated PayPal Mobile SDK in iOS app, but it does not show list of Shipping address (list of default address user is having in his account) so that he can choose any one of them. I can only see the list of dummy cards to select and make a payment.

**Comment by shabi** [comment]
Can I go with PayPal Express checkout integration in my iOS app? any demo/sample code?

**Comment by shabi** [comment]
How to enable Paypal credit option in PayPal Mobile SDK for iOS?

**Comment by bluk** [comment]
@shabi Please ensure that the [`payPalShippingAddressOption`](https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalConfiguration.h#L63) is set correctly. The PayPal Credit option is not available in this PayPal Mobile SDK for iOS.

I would also investigate if you can integrate with [Express Checkout with the Braintree SDK](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/client-side/ios/v4/) (which uses a subset of the Braintree SDK but does not require a Braintree account).

Or directly integrate with [Braintree Payments](https://www.braintreepayments.com/) for credit card, PayPal, and other payment methods. There is a demo app included in the [Braintree iOS SDK project](https://github.com/braintree/braintree_ios). PayPal Credit is available with a direct integration, but there are different options for integration. I would suggest contacting [Braintree Sales](https://www.braintreepayments.com/contact/sales) if you wish to integrate with Braintree and want to use PayPal Credit.

I'm going to lock this issue since the original issue is different and this discussion is unrelated. If there are integration questions for this SDK, please open a new issue. Thanks.
