### ISSUE TITLE
Successfully installed via cocoapods but Error "Use of Unresolved Identifier"

### ISSUE THREAD

**Issue by umair151** [paypal/PayPal-iOS-SDK#512]
I have successfully installed sdk via cocoapod but unable to use in code with error "Use of unresolved identifier PayPal*****"

**Comment by bluk** [comment]
Hello. Are you using Objective-C or Swift? Are the imports correct? You may want to see the sample app in this repository for an example and see if that works for you.

**Comment by umair151** [comment]
I am using swift and exactly following the sample app.

**Comment by jflaurin** [comment]
I get the same "Use of unresolved identifier" error.  I installed via cocoaPod + I code in Swift 3

**Comment by bluk** [comment]
For the Podfile, are you using `use_frameworks!`? Also, are either of you using Xcode 8.2.x or 8.3?

**Comment by umair151** [comment]
I am using `use_frameworks!` and Xcode is `8.2.1`

**Comment by bluk** [comment]
Just to make sure, do you have an [Objective-C bridging header](https://github.com/paypal/PayPal-iOS-SDK/blob/master/SampleApp-Swift/PayPal-iOS-SDK-Sample-App/PayPal-iOS-SDK-Sample-App-Bridging-Header.h) with the `#import "PayPalMobile.h"`?

The easiest way to create one is probably to add a new Objective-C class and have Xcode automatically create the bridging header. Otherwise, create a new header file with the correct name `<your project>-Bridging-Header.h` and in your target's build settings for `Objective-C Bridging Header`, be sure to set the value to the header file's location.

For your Podfile, also be sure that you have included this SDK's declaration in every relevant target:

```
target 'YourTarget' do
  pod 'PayPal-iOS-SDK'
end

target 'YourTargetTests' do
  pod 'PayPal-iOS-SDK'
end
```

This is partially due to the usage of the prebuilt static library in this SDK.

If you are still encountering an issue, please leave a comment and we can reopen the issue. Note if this is a new integration for a single payment checkout, you may want to investigate [PayPal Express Checkout with the Braintree SDK](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) which uses the open source Braintree iOS client SDK.

**Comment by umair151** [comment]
Thank you so much!  I was missing the bridging header.

**Comment by siddhesh12** [comment]
If possible please add this step in readme file. I wasted 1 hour in investigating this issue. Simply adding bridging header file solved my problem. You don't have to import anything in your main project.

**Comment by xiaoleih41** [comment]
@siddhesh12 Will you be interested in submitting a pull request on this?
