### ISSUE TITLE
Payment issue with sandbox - 400 error

### ISSUE THREAD

**Issue by faraxnak** [paypal/PayPal-iOS-SDK#513]
Mode (Sandbox):
PayPal iOS SDK Version:2.16.1
iOS Version and Device (iOS 10.2 on an iPhone 6):
PayPal-Debug-ID(s) (from any logs):PayPal Debug-ID: 2cda7c7f6cc19, 2cda7c7f6cc19
### Issue description

I'm trying to test a credit card payment in sandbox mode but with no luck. the error is "System error. please try again later." and the log is:
PayPal SDK: Request has failed with error: UNKNOWN_ERROR - System error. Please try again later. (400) | PayPal Debug-ID: 2cda7c7f6cc19, 2cda7c7f6cc19 [sandbox, PayPal iOS SDK 2.16.1]

**Comment by pp-randy** [comment]
REST Credit Card works for US and UK accounts at this time please see https://developer.paypal.com/docs/faq/#international-developer-questions

A Braintree integration might work https://www.braintreepayments.com/en-hk/products/braintree-direct

**Comment by ReemaSpaceo** [comment]
**PayPal SDK: Request has failed with error: PAYEE_ACCOUNT_INVALID - 
Vendor account does not have a confirmed email. (400) |
 PayPal Debug-ID: c81b833cd6220, c81b833cd6220 
[sandbox, PayPal iOS SDK 2.16.1]**

I am trying to test with credit card in sandbox mode but it is not working while login with email is working fine .

**Comment by xiaoleih41** [comment]
It says the receiver doesn't have a confirmed email address. Which sandbox account did you use as the *payee*? Also, please make sure to upgrade the sandbox account from your **developer dashboard** to **pro** in order to receive credit card payment. Just go to developer.paypal.com, click **Dashboard**, then **Sandbox** > **Accounts**, Select the payee sandbox account and make the **Upgrade to Pro** inside of the **profile**.

**Comment by ReemaSpaceo** [comment]
Hello Xiaolei Wheelock

Thanks for the replay

Can you please do let me know from where I will get that upgrade option and confirm vendor email. because I followed you steps but I didn't find **Upgrade to Pro** option inside the **profile.
It is showing Account Type Business Pro.
![screen shot 2017-06-26 at 10 31 09 am](https://user-images.githubusercontent.com/22314587/27525345-9a4dcf82-5a5a-11e7-8491-9fd167073c19.png)
**

**Comment by xiaoleih41** [comment]
@ReemaSpaceo The REST app is under a different PayPal sandbox account. Can you double check your app credential again? If it's a US account, it should work.

**Comment by krishnasolankiD** [comment]
I am getting  error " PayPal SDK: Request has failed with error: UNKNOWN_ERROR - System error. Please try again later. (400) | PayPal Debug-ID: 3e0da96568684, 3e0da96568684 [live, PayPal iOS SDK 2.14.2]" 
for paywithcard option in live
