### ISSUE TITLE
PayPal app not launched after PayPal payment method selected by user

### ISSUE THREAD

**Issue by ramunasjurgilas** [paypal/PayPal-iOS-SDK#551]
I did integrate PayPal to my project using pod 'Braintree/PayPal'.
When user chooses to make payment throw PayPal user is not redirected to the PayPal app. Instead it opens view controller within my app. Is it bug or it should be like this for PayPal?

In [documentation](https://developers.braintreepayments.com/guides/client-sdk/setup/ios/v4 ) is written that needs to provide URL schemes which are needed for switching from one app to another. 

I am using latest Braintree SDK:
  - Braintree/Card (4.9.3):
    - Braintree/Core
  - Braintree/Core (4.9.3)
  - Braintree/PayPal (4.9.3):
    - Braintree/Core
    - Braintree/PayPalOneTouch
  - Braintree/PayPalDataCollector (4.9.3):
    - Braintree/Core
    - Braintree/PayPalUtils
  - Braintree/PayPalOneTouch (4.9.3):
    - Braintree/Core
    - Braintree/PayPalDataCollector
    - Braintree/PayPalUtils
  - Braintree/PayPalUtils (4.9.3)
  - Braintree/UnionPay (4.9.3):
    - Braintree/Card
    - Braintree/Core
  - BraintreeDropIn (5.2.3):
    - BraintreeDropIn/DropIn (= 5.2.3)
  - BraintreeDropIn/DropIn (5.2.3):
    - Braintree/Card (~> 4.0)
    - Braintree/Core (~> 4.0)
    - Braintree/UnionPay (~> 4.0)
    - BraintreeDropIn/UIKit
  - BraintreeDropIn/UIKit (5.2.3)

**Comment by bluk** [comment]
@ramunasjurgilas The PayPal app is not used for app switching currently. It is expected that a `SFSafariViewController` or `SFAuthenticationSession` is presented. The custom URL schemes are required to switch back from those flows to your app.

For related issues, you may want to open issues on the [Braintree iOS repository](https://github.com/braintree/braintree_ios) since a few different folks monitor each repository.
