### ISSUE TITLE
Crash: -[PPRiskConfiguration mgIdKey]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by jontelang** [paypal/PayPal-iOS-SDK#553]
### General information

* SDK/Library version: 2.18.0
* Environment: Only tried in development environment
* iOS Version and Device: See below
* Integration type and version: Cocoapods 1.2.0

### Issue description

This is maybe related to #547 but I broke it out into a new ticket.

After updating to 2.18.0, all devices crash on initializing the environment, stating the following:

    2017-10-24 11:59:32.716 HotelQuickly[1240:381979] -[PPRiskConfiguration mgIdKey]: unrecognized selector sent to instance 0x1701fc60
    2017-10-24 11:59:37.340 HotelQuickly[1240:381979] Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PPRiskConfiguration mgIdKey]: unrecognized selector sent to instance 0x1701fc60'
    First throw call stack:
    (0x20f69b0b 0x20726dff 0x20f6f455 0x20f6d0ab 0x20e97298 0x359155 0x3587e5 0x357495 0x3564ff 0x355d8d 0x22e57a9 0x355d2f 0x3287af 0x3278c9 0x22e4b93 0x22e57a9 0x327893 0x327a85 0xfe219 0xfd37d 0x255bda6f 0x257e7287 0x257eb241 0x257ff811 0x257e8767 0x22637bf7 0x22637aa7 0x22637da5 0x20f2b9e7 0x20f2b5d7 0x20f2993f 0x20e781c9 0x20e77fbd 0x255b6f37 0x255b1435 0x1f5f43 0x20b24873)
    libc++abi.dylib: terminating with uncaught exception of type NSException

So far this happens on

**Jailbroken**  
iPhone 5s 9.0.2  
iPhone 5s 10.2  

**Not jailbroken**  
iPhone 5 (32bit) 9.3.4  
iPhone 5s 10.2  
iPhone 5s  8.4.1  

Our initialization method is currently done in AppDelegate didFinishLaunching like this

    [PayPalMobile initializeWithClientIdsForEnvironments:
        @{PayPalEnvironmentProduction : PAYPAL_PRODUCTION_CLIENT_ID,
          PayPalEnvironmentSandbox    : PAYPAL_SANDBOX_CLIENT_ID}];

I'm not sure if this should be a new ticket maybe, since the crash is different.

**Comment by bluk** [comment]
Do you set any specific compiler flags, or are you using any other 3rd party dependencies?

**Comment by jontelang** [comment]
Yes, a lot of other pods (here's our podfile.lock https://gist.github.com/jontelang/3fefd06313889161de909ef413315c69)

As for compiler flags, nothing specially added ourselves as far as I now, any clues what _could_ do anything?

Anything else I can do to narrow anything down?

**Comment by jontelang** [comment]
I've been able to replicate the issue and the issue is when using an older version of Braintree together with the newer version of PayPal. We use older version because of.. hardware/software issues when archiving on older/newer devices.

Perhaps a non issue, but here is a project if you want to see it in action: https://github.com/jontelang/PayPalCrashExample you can see the versions used in the Podfile, and switching between them will turn the crash on/off.

There are still logs about duplicated implementation even when not crashing, so maybe there is potential for similar issues?

e.g.

    objc[8571]: Class PPRiskComponent is implemented in both /private/var/mobile/Containers/Bundle/Application/F527B7CF-EB96-4996-99B2-6371A87D90C8/PayPalCrashExample.app/Frameworks/Braintree.framework/Braintree and /var/mobile/Containers/Bundle/Application/F527B7CF-EB96-4996-99B2-6371A87D90C8/PayPalCrashExample.app/PayPalCrashExample. One of the two will be used. Which one is undefined.

**Comment by bluk** [comment]
@jontelang Great that you were able to track this down. As you suspect, both libraries depend on some common code, and if they are not at the same version, then there will be issues. If you still encounter issues that force you to use an older version of Braintree, you may want to open an issue with the [braintree-ios](https://github.com/braintree/braintree_ios/issues) repository or contact [Braintree Support](https://developers.braintreepayments.com/forms/contact).

Since you're already using Braintree, I would look into directly using Braintree for PayPal (for vaulted payments and single payment checkout) or to use [Express Checkout with Braintree SDKs](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) if you're doing single payment checkout. This PayPal-iOS-SDK has recently been deprecated and while existing integrations will be supported, it may be beneficial for you to only depend on the Braintree SDK (app size and a simpler integration).

**Comment by jontelang** [comment]
Thanks for the pointers, I will definitely take a look at doing this.

I guess we can close the ticket now as both issue, cause and fix is found.
