### ISSUE TITLE
I am trying to get the API to work in "Live" mode, I have had no issues with integrating the SDK through Sandbox, but once I switch to live I get: Unauthorized Payment Paypal error 401 LIVE MODE also in my account product i have this:

### ISSUE THREAD

**Issue by boufalghala** [paypal/PayPal-iOS-SDK#559]
<img width="959" alt="capture d ecran 2017-11-21 a 16 58 55" src="https://user-images.githubusercontent.com/31658578/33121046-105e8f8e-cf74-11e7-86f9-d9f71429bc43.png">

### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* iOS Version and Device: 
* Integration type and version:

**Comment by xiaoleih41** [comment]
Are you trying to make future payment call? It looks like it is not enabled. Please submit the application by clicking the enable link and start the process. As the feature is limited release so if it's not approved, you may consider to integrate Braintree SDK instead. It supports both credit card and PayPal payments. Please consider to call customer service first and request a sales person to walk you through so that you can get help on feature approval as well as technical support.

**Comment by boufalghala** [comment]
@xiaoleih41  yes I try to make future payment but my problem is how can enable future payment when I click a it this is when i click a it this is result

[
<img width="942" alt="capture d ecran 2017-11-20 a 14 51 57" src="https://user-images.githubusercontent.com/31658578/33161938-082b9e0c-d027-11e7-9fbf-282b669f5f1b.png">
how I can enable this plz without integrate Braintree and with rest api in sandbox it is work  I  need help

**Comment by xiaoleih41** [comment]
You can click `contact us` to contact the them. As I have stated before, this feature has been deprecated or moved to limited release. I am not sure if you will be approved or not. We have newer feature available for to replace this. You can look into Braintree SDK for pay with paypal option instead.

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been given.
