### ISSUE TITLE
There is a problem communicating with the PayPal servers  with live transaction

### ISSUE THREAD

**Issue by ronakcc** [paypal/PayPal-iOS-SDK#74]
Hi All 
Thanks to all
Please give me solution ASAP given below error
"There is a problem communicating with the PayPal servers . Please try again"

In Sandbox working propery but error in live transaction.
I use all version Pay Pal iOS SDK but same error :(

below is my app detail
Appname - iOS-SDK-Sample-App
# define kPayPalClientId @"ATxiMhAPUOJ6M79LkN4QWUta4Q26GRFptJz7VOWtUhl6Q34-8lkYha9Xd_tq"
# define kPayPalReceiverEmail @"begona.garcia@elitemobile.com"

Thanks 
ronak patel

**Comment by tolomir** [comment]
Hi there,
I'm with the same problem! What information do you need to check the validity of my account?
In Sandbox is working properly but no way to get to work in Live mode. I get the same error message:
"There was a problem communicating with the PayPal servers . Please try again"

I also have been in touch with PayPal tech center and everything seems ok there!
I need a solution because the app cannot go to market if is not able to accept Payments.

Thank you!

**Comment by bluk** [comment]
@tolomir Ensure that your live account has the same capabilities as your sandbox account via the [developer dashboard](https://developer.paypal.com/developer/accountStatus/). And also please ensure you are using the right credentials for the live account vs. sandbox. [MTS support](https://www.paypal-techsupport.com) may also help since they have access to more information about your account.

If you have a `PayPal-Debug-Id` from a response and any other debug information (like the version of the SDK you are using), that would also be helpful.

**Comment by tolomir** [comment]
@bluk Thank you so much for your answer. I've already been in touch with the MTS support and their advise is to ensure that I am using "paypal" as a "payment_method" and not "credit_card" that is only allowed to PRO accounts.

"payment_method":"paypal"

I don't know where to find this  "payment_method" configuration in the plugin. Could you please tell me where can I find it?

Thanks again!

**Comment by tolomir** [comment]
@bluk...  by the way... the SDK version I'm using is com.paypal.cordova.mobilesdk 3.1.13
Thanks!

**Comment by bluk** [comment]
@tolomir Can you try using the latest version of the cordova plugin `3.1.18`. There was a fix for a bug where it couldn't communicate with live in 3.1.13. Also, I suggest using the [PayPal-Cordova-Plugin](https://github.com/paypal/PayPal-Cordova-Plugin) GitHub repository for investigating/reporting these issues in addition to this repository.

**Comment by tolomir** [comment]
@bluk Thanks for your answer. I have updated to 3.1.18 and also been in touch with Paypal-Techsupport. The issue seems to be the configuration in my account to accept Direct Credit Card Payments in LIVE mode. But the problem I have is that there is no way to Enable this option. When I try to do it I get this message:

"Note: Direct credit card processing is not available for you when using REST APIs. Your live credentials are inoperable for direct credit card processing for your country but your test credentials are enabled for sandbox testing."

Isn't it wierd? I don't know what else to do to accept Credit Card Payments in my app. Any suggestion?

Thanks again!

![settings](https://cloud.githubusercontent.com/assets/8638854/11140830/2db28e0a-89df-11e5-8e71-9645c8965081.jpg)

**Comment by bluk** [comment]
@tolomir Sorry, I don't have access to account information. You will need to go through [Merchant Technical Support](https://www.paypal-techsupport.com) to see why you cannot enable Direct Credit Card payments, but I would also check if your country is in the [supported list](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/#direct-credit-card-payments) for [direct credit card payments](https://developer.paypal.com/docs/integration/direct/accept-credit-cards/).

**Comment by tolomir** [comment]
@bluk Thank you so much! Despite the fact that the EURO is in the supported list It happens to be that according to the Technical Support Spain does NOT support direct credit card payments in REST_API.... I can't believe it! 
The Technical support recommends me a solution called Paypal Pro that is not related with the plugin I was trying to use.  Did you know it? Sorry, but I am still shocked! 

Well, just a question @bluk.... Is there any way in the plugin settings to just accept Paypal Account payments and not Credit card ones? 

Thank you so much for your help!

**Comment by bluk** [comment]
@tolomir You can toggle accepting credit cards in the `PayPalConfiguration` object you create. It has [a property `acceptCreditCards`](https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalConfiguration.h#L52) which you can set to `NO` to disable credit cards (at that point, you can choose to not link the `CardIO` libraries as well)

You can see the included Samples in this repository (with and without +card.io) for an example. Hope that helps.
